name: CI/CD Deploy to VPS

on:
  push:
    branches:
      - deploy

env:
  DOCKER_IMAGE: thepujon/simple_blog_backend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # log in to docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # build docker image
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.DOCKER_IMAGE }}:latest .

      # push docker image
      - name: Push Docker Image
        run: |
          docker push ${{ env.DOCKER_IMAGE }}:latest

      # deploy to VPS
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /opt/wonder-emporium
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml pull
            docker compose -f docker-compose.yaml -f docker-compose.prod.yaml up -d --remove-orphans
